"""Initial migration

Revision ID: 34258fd52acb
Revises: 
Create Date: 2025-05-20 20:14:07.796013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34258fd52acb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('interpreter_id', sa.Integer(), nullable=True),
    sa.Column('information', sa.String(), nullable=True),
    sa.Column('cliniko_appointment_id', sa.BigInteger(), nullable=False),
    sa.Column('cliniko_practitioner_id', sa.BigInteger(), nullable=True),
    sa.Column('patient_id', sa.BigInteger(), nullable=True),
    sa.Column('cliniko_account_id', sa.Integer(), nullable=False),
    sa.Column('cliniko_appointment_type_id', sa.BigInteger(), nullable=True),
    sa.Column('language_id', sa.Integer(), nullable=True),
    sa.Column('interpreter_availability_id', sa.BigInteger(), nullable=True),
    sa.Column('practitioner_availability_id', sa.BigInteger(), nullable=True),
    sa.Column('cancellation_reason_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('booked', sa.Boolean(), nullable=True),
    sa.Column('canceled', sa.Boolean(), nullable=True),
    sa.Column('missed', sa.Boolean(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('add_interpreter', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['cancellation_reason_id'], ['cancellation_reasons.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cliniko_account_id'], ['cliniko_accounts.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cliniko_appointment_type_id'], ['cliniko_appointment_types.cliniko_appointment_type_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cliniko_practitioner_id'], ['practitioners.cliniko_practitioner_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['interpreter_availability_id'], ['availability.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['interpreter_id'], ['interpreters.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['practitioner_availability_id'], ['practitioners_availability.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'cliniko_appointment_id', 'cliniko_account_id'),
    sa.UniqueConstraint('cliniko_appointment_id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('cancellation_reasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cliniko_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('api_key', sa.String(), nullable=True),
    sa.Column('cliniko_id_name', sa.String(), nullable=True),
    sa.Column('business_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cliniko_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cliniko_accounts_name'), ['name'], unique=True)

    op.create_table('genders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gender', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('languages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('short_name', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('full_name'),
    sa.UniqueConstraint('short_name')
    )
    op.create_table('practitioners_availability',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cliniko_practitioner_id', sa.BigInteger(), nullable=False),
    sa.Column('cliniko_appointment_id', sa.BigInteger(), nullable=True),
    sa.Column('cliniko_account_id', sa.Integer(), nullable=False),
    sa.Column('booked', sa.Boolean(), nullable=True),
    sa.Column('canceled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cliniko_account_id'], ['cliniko_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cliniko_appointment_id'], ['appointments.cliniko_appointment_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cliniko_practitioner_id'], ['practitioners.cliniko_practitioner_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cliniko_practitioner_id', 'timestamp', name='uq_practitioner_datetime_appointment')
    )
    op.create_table('cliniko_appointment_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('cliniko_appointment_type_id', sa.BigInteger(), nullable=False),
    sa.Column('cliniko_account_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cliniko_account_id'], ['cliniko_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'cliniko_appointment_type_id'),
    sa.UniqueConstraint('cliniko_appointment_type_id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('interpreters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('tz', sa.String(), nullable=False),
    sa.Column('U', sa.Boolean(), nullable=True),
    sa.Column('R', sa.Boolean(), nullable=True),
    sa.Column('first_lang_id', sa.Integer(), nullable=False),
    sa.Column('second_lang_id', sa.Integer(), nullable=False),
    sa.Column('mental_apts', sa.Boolean(), nullable=True),
    sa.Column('cliniko_medical_id', sa.BigInteger(), nullable=True),
    sa.Column('cliniko_mental_id', sa.BigInteger(), nullable=True),
    sa.Column('auth0_id', sa.String(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['first_lang_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['second_lang_id'], ['languages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year_of_birth', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('tz', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('cliniko_medical_id', sa.BigInteger(), nullable=True),
    sa.Column('cliniko_mental_id', sa.BigInteger(), nullable=True),
    sa.Column('first_language', sa.String(), nullable=False),
    sa.Column('second_language', sa.String(), nullable=True),
    sa.Column('auth0_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_lang_id', sa.Integer(), nullable=True),
    sa.Column('second_lang_id', sa.Integer(), nullable=True),
    sa.Column('gender_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['first_lang_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['gender_id'], ['genders.id'], ),
    sa.ForeignKeyConstraint(['second_lang_id'], ['languages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cliniko_medical_id'),
    sa.UniqueConstraint('cliniko_mental_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('practitioners',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cliniko_practitioner_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('tz', sa.String(), nullable=False),
    sa.Column('cliniko_account_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('specialization', sa.String(), nullable=True),
    sa.Column('information', sa.String(), nullable=True),
    sa.Column('first_lang_id', sa.Integer(), nullable=False),
    sa.Column('second_lang_id', sa.Integer(), nullable=False),
    sa.Column('third_lang_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliniko_account_id'], ['cliniko_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['first_lang_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['second_lang_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['third_lang_id'], ['languages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cliniko_practitioner_id')
    )
    op.create_table('availability',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('interpreter_id', sa.Integer(), nullable=False),
    sa.Column('mental_apts', sa.Boolean(), nullable=True),
    sa.Column('U', sa.Boolean(), nullable=True),
    sa.Column('R', sa.Boolean(), nullable=True),
    sa.Column('booked', sa.Boolean(), nullable=True),
    sa.Column('canceled', sa.Boolean(), nullable=True),
    sa.Column('cliniko_appointment_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['interpreter_id'], ['interpreters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('availability', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_availability_cliniko_appointment_id'), ['cliniko_appointment_id'], unique=False)

    op.create_table('genders_patients',
    sa.Column('gender_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gender_id'], ['genders.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('gender_id', 'patient_id')
    )
    op.create_table('languages_interpreters',
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('interpreter_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['interpreter_id'], ['interpreters.id'], ),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.PrimaryKeyConstraint('language_id', 'interpreter_id')
    )
    op.create_table('languages_patients',
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('language_id', 'patient_id')
    )
    op.create_table('languages_practitioners',
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['practitioners.id'], ),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.PrimaryKeyConstraint('language_id', 'doctor_id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('sender', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('messenger', sa.String(length=20), nullable=False),
    sa.Column('message_metadata', sa.JSON(), nullable=True),
    sa.Column('attachment_url', sa.Text(), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliniko_medical_id', sa.BigInteger(), nullable=True),
    sa.Column('cliniko_mental_id', sa.BigInteger(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('interpreter_id', sa.Integer(), nullable=True),
    sa.Column('appointment_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('assigned_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('translated_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('download_info', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['interpreter_id'], ['interpreters.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('services_practitioners',
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('practitioner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['practitioner_id'], ['practitioners.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['cliniko_appointment_types.id'], ),
    sa.PrimaryKeyConstraint('service_id', 'practitioner_id')
    )
    op.create_table('treatment_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('practitioner_id', sa.BigInteger(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('interpreter_id', sa.Integer(), nullable=True),
    sa.Column('appointment_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('assigned_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('translated_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('download_info', sa.String(), nullable=True),
    sa.Column('cliniko_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['interpreter_id'], ['interpreters.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cliniko_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('treatment_notes')
    op.drop_table('services_practitioners')
    op.drop_table('patient_attachments')
    op.drop_table('messages')
    op.drop_table('languages_practitioners')
    op.drop_table('languages_patients')
    op.drop_table('languages_interpreters')
    op.drop_table('genders_patients')
    with op.batch_alter_table('availability', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_availability_cliniko_appointment_id'))

    op.drop_table('availability')
    op.drop_table('practitioners')
    op.drop_table('patients')
    op.drop_table('interpreters')
    op.drop_table('cliniko_appointment_types')
    op.drop_table('practitioners_availability')
    op.drop_table('languages')
    op.drop_table('genders')
    with op.batch_alter_table('cliniko_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cliniko_accounts_name'))

    op.drop_table('cliniko_accounts')
    op.drop_table('cancellation_reasons')
    op.drop_table('appointments')
    # ### end Alembic commands ###
